// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpellSinger.Data;

#nullable disable

namespace SpellSinger.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251205193230_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CharacterClassSpell", b =>
                {
                    b.Property<Guid>("CharacterClassesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellsId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterClassesId", "SpellsId");

                    b.HasIndex("SpellsId");

                    b.ToTable("CharacterClassSpell");
                });

            modelBuilder.Entity("ConditionSpell", b =>
                {
                    b.Property<Guid>("ConditionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellsId")
                        .HasColumnType("uuid");

                    b.HasKey("ConditionsId", "SpellsId");

                    b.HasIndex("SpellsId");

                    b.ToTable("ConditionSpell");
                });

            modelBuilder.Entity("DamageTypeSpell", b =>
                {
                    b.Property<Guid>("DamageTypesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellsId")
                        .HasColumnType("uuid");

                    b.HasKey("DamageTypesId", "SpellsId");

                    b.HasIndex("SpellsId");

                    b.ToTable("DamageTypeSpell");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SpellSinger.Domain.EntityBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("EntityBase");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("SpellSinger.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SpellSinger.Domain.CharacterSpell", b =>
                {
                    b.HasBaseType("SpellSinger.Domain.EntityBase");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPrepared")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SpellId")
                        .HasColumnType("uuid");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SpellId");

                    b.ToTable("CharacterSpells");
                });

            modelBuilder.Entity("SpellSinger.Domain.ClassProgression", b =>
                {
                    b.HasBaseType("SpellSinger.Domain.EntityBase");

                    b.Property<Guid>("CharacterClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasIndex("CharacterClassId");

                    b.HasIndex("CharacterId");

                    b.ToTable("ClassProgressions");
                });

            modelBuilder.Entity("SpellSinger.Domain.NamedEntity", b =>
                {
                    b.HasBaseType("SpellSinger.Domain.EntityBase");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.ToTable("NamedEntity");
                });

            modelBuilder.Entity("SpellSinger.Domain.ActionCategory", b =>
                {
                    b.HasBaseType("SpellSinger.Domain.NamedEntity");

                    b.ToTable("ActionCategories", (string)null);
                });

            modelBuilder.Entity("SpellSinger.Domain.Character", b =>
                {
                    b.HasBaseType("SpellSinger.Domain.NamedEntity");

                    b.Property<string>("Background")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("SpellSinger.Domain.CharacterClass", b =>
                {
                    b.HasBaseType("SpellSinger.Domain.NamedEntity");

                    b.Property<int>("HitDie")
                        .HasColumnType("integer");

                    b.ToTable("CharacterClasses", (string)null);
                });

            modelBuilder.Entity("SpellSinger.Domain.Condition", b =>
                {
                    b.HasBaseType("SpellSinger.Domain.NamedEntity");

                    b.ToTable("Conditions", (string)null);
                });

            modelBuilder.Entity("SpellSinger.Domain.DamageType", b =>
                {
                    b.HasBaseType("SpellSinger.Domain.NamedEntity");

                    b.ToTable("DamageTypes", (string)null);
                });

            modelBuilder.Entity("SpellSinger.Domain.School", b =>
                {
                    b.HasBaseType("SpellSinger.Domain.NamedEntity");

                    b.ToTable("Schools", (string)null);
                });

            modelBuilder.Entity("SpellSinger.Domain.SourceBook", b =>
                {
                    b.HasBaseType("SpellSinger.Domain.NamedEntity");

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("timestamp without time zone");

                    b.ToTable("SourceBooks", (string)null);
                });

            modelBuilder.Entity("SpellSinger.Domain.Spell", b =>
                {
                    b.HasBaseType("SpellSinger.Domain.NamedEntity");

                    b.Property<Guid>("ActionCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("AreaShape")
                        .HasColumnType("text");

                    b.Property<int?>("AreaSize")
                        .HasColumnType("integer");

                    b.Property<string>("AtHigherLevels")
                        .HasColumnType("text");

                    b.Property<string>("AttackType")
                        .HasColumnType("text");

                    b.Property<string>("CastingTimeText")
                        .HasColumnType("text");

                    b.Property<string>("DamageDice")
                        .HasColumnType("text");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<bool>("HasMaterialComponent")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSomaticComponent")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasVerbalComponent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConcentration")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRitual")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialComponentDescription")
                        .HasColumnType("text");

                    b.Property<string>("Range")
                        .HasColumnType("text");

                    b.Property<string>("SaveAbility")
                        .HasColumnType("text");

                    b.Property<string>("SaveEffect")
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceBookId")
                        .HasColumnType("uuid");

                    b.Property<string>("UpcastDice")
                        .HasColumnType("text");

                    b.HasIndex("ActionCategoryId");

                    b.HasIndex("SchoolId");

                    b.HasIndex("SourceBookId");

                    b.ToTable("Spells", (string)null);
                });

            modelBuilder.Entity("CharacterClassSpell", b =>
                {
                    b.HasOne("SpellSinger.Domain.CharacterClass", null)
                        .WithMany()
                        .HasForeignKey("CharacterClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpellSinger.Domain.Spell", null)
                        .WithMany()
                        .HasForeignKey("SpellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConditionSpell", b =>
                {
                    b.HasOne("SpellSinger.Domain.Condition", null)
                        .WithMany()
                        .HasForeignKey("ConditionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpellSinger.Domain.Spell", null)
                        .WithMany()
                        .HasForeignKey("SpellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DamageTypeSpell", b =>
                {
                    b.HasOne("SpellSinger.Domain.DamageType", null)
                        .WithMany()
                        .HasForeignKey("DamageTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpellSinger.Domain.Spell", null)
                        .WithMany()
                        .HasForeignKey("SpellsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SpellSinger.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SpellSinger.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpellSinger.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SpellSinger.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpellSinger.Domain.CharacterSpell", b =>
                {
                    b.HasOne("SpellSinger.Domain.Character", "Character")
                        .WithMany("Spells")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpellSinger.Domain.EntityBase", null)
                        .WithOne()
                        .HasForeignKey("SpellSinger.Domain.CharacterSpell", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpellSinger.Domain.Spell", "Spell")
                        .WithMany()
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("SpellSinger.Domain.ClassProgression", b =>
                {
                    b.HasOne("SpellSinger.Domain.CharacterClass", "CharacterClass")
                        .WithMany()
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpellSinger.Domain.Character", "Character")
                        .WithMany("Classes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpellSinger.Domain.EntityBase", null)
                        .WithOne()
                        .HasForeignKey("SpellSinger.Domain.ClassProgression", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("CharacterClass");
                });

            modelBuilder.Entity("SpellSinger.Domain.NamedEntity", b =>
                {
                    b.HasOne("SpellSinger.Domain.EntityBase", null)
                        .WithOne()
                        .HasForeignKey("SpellSinger.Domain.NamedEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpellSinger.Domain.ActionCategory", b =>
                {
                    b.HasOne("SpellSinger.Domain.NamedEntity", null)
                        .WithOne()
                        .HasForeignKey("SpellSinger.Domain.ActionCategory", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpellSinger.Domain.Character", b =>
                {
                    b.HasOne("SpellSinger.Domain.NamedEntity", null)
                        .WithOne()
                        .HasForeignKey("SpellSinger.Domain.Character", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpellSinger.Domain.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SpellSinger.Domain.CharacterClass", b =>
                {
                    b.HasOne("SpellSinger.Domain.NamedEntity", null)
                        .WithOne()
                        .HasForeignKey("SpellSinger.Domain.CharacterClass", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpellSinger.Domain.Condition", b =>
                {
                    b.HasOne("SpellSinger.Domain.NamedEntity", null)
                        .WithOne()
                        .HasForeignKey("SpellSinger.Domain.Condition", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpellSinger.Domain.DamageType", b =>
                {
                    b.HasOne("SpellSinger.Domain.NamedEntity", null)
                        .WithOne()
                        .HasForeignKey("SpellSinger.Domain.DamageType", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpellSinger.Domain.School", b =>
                {
                    b.HasOne("SpellSinger.Domain.NamedEntity", null)
                        .WithOne()
                        .HasForeignKey("SpellSinger.Domain.School", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpellSinger.Domain.SourceBook", b =>
                {
                    b.HasOne("SpellSinger.Domain.NamedEntity", null)
                        .WithOne()
                        .HasForeignKey("SpellSinger.Domain.SourceBook", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpellSinger.Domain.Spell", b =>
                {
                    b.HasOne("SpellSinger.Domain.ActionCategory", "ActionCategory")
                        .WithMany("Spells")
                        .HasForeignKey("ActionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpellSinger.Domain.NamedEntity", null)
                        .WithOne()
                        .HasForeignKey("SpellSinger.Domain.Spell", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpellSinger.Domain.School", "School")
                        .WithMany("Spells")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpellSinger.Domain.SourceBook", "SourceBook")
                        .WithMany("Spells")
                        .HasForeignKey("SourceBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionCategory");

                    b.Navigation("School");

                    b.Navigation("SourceBook");
                });

            modelBuilder.Entity("SpellSinger.Domain.User", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("SpellSinger.Domain.ActionCategory", b =>
                {
                    b.Navigation("Spells");
                });

            modelBuilder.Entity("SpellSinger.Domain.Character", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Spells");
                });

            modelBuilder.Entity("SpellSinger.Domain.School", b =>
                {
                    b.Navigation("Spells");
                });

            modelBuilder.Entity("SpellSinger.Domain.SourceBook", b =>
                {
                    b.Navigation("Spells");
                });
#pragma warning restore 612, 618
        }
    }
}
